"""add composite indexes for query optimization

Revision ID: cc0bfff7d6fb
Revises: 36190d67d906
Create Date: 2026-04-03 15:56:25.167408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0bfff7d6fb'
down_revision: Union[str, None] = '36190d67d906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_invoices_policy_status', 'invoices', ['policy_id', 'status'], unique=False)
    op.create_index('ix_invoices_status_due_date', 'invoices', ['status', 'due_date'], unique=False)
    op.create_index('ix_policies_policyholder_status', 'policies', ['policyholder_id', 'status'], unique=False)
    op.create_index('ix_policies_status_created', 'policies', ['status', 'created_at'], unique=False)
    op.create_index('ix_quotes_status_created', 'quotes', ['status', 'created_at'], unique=False)
    op.create_index('ix_underwriting_reviews_status_created', 'underwriting_reviews', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_underwriting_reviews_status_created', table_name='underwriting_reviews')
    op.drop_index('ix_quotes_status_created', table_name='quotes')
    op.drop_index('ix_policies_status_created', table_name='policies')
    op.drop_index('ix_policies_policyholder_status', table_name='policies')
    op.drop_index('ix_invoices_status_due_date', table_name='invoices')
    op.drop_index('ix_invoices_policy_status', table_name='invoices')
    # ### end Alembic commands ###
