"""add users table

Revision ID: 36190d67d906
Revises: 983338379ccf
Create Date: 2026-04-03 02:02:24.453828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36190d67d906'
down_revision: Union[str, None] = '983338379ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'", name='check_email_format'),
    sa.CheckConstraint("role IN ('admin', 'underwriter', 'agent', 'customer')", name='check_valid_role'),
    sa.PrimaryKeyConstraint('id'),
    comment='User table for authentication and authorization'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Format: INV-YYYYMMDD-XXXX',
               existing_nullable=False)
    op.alter_column('invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Total amount to be paid',
               existing_nullable=False)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               comment='Amount paid so far (supports partial payments)',
               existing_nullable=False)
    op.alter_column('invoices', 'paid_date',
               existing_type=sa.DATE(),
               comment='Date when invoice was fully paid',
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'sent', 'paid', 'overdue', 'partially_paid', 'cancelled', 'refunded', name='invoice_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Internal transaction ID',
               existing_nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Stripe PaymentIntent ID (e.g., pi_...)',
               existing_nullable=True)
    op.alter_column('payments', 'stripe_charge_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Stripe Charge ID (e.g., ch_...)',
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', 'refunded', 'partially_refunded', 'cancelled', name='payment_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'failure_reason',
               existing_type=sa.TEXT(),
               comment='Reason for payment failure',
               existing_nullable=True)
    op.alter_column('payments', 'payment_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Store Stripe webhook data and additional info',
               existing_nullable=True)
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.create_unique_constraint(None, 'payments', ['transaction_id'])
    op.create_unique_constraint(None, 'payments', ['stripe_payment_intent_id'])
    op.drop_index(op.f('ix_policyholders_email'), table_name='policy_holders')
    op.drop_index(op.f('ix_policyholders_first_name'), table_name='policy_holders')
    op.drop_index(op.f('ix_policyholders_id'), table_name='policy_holders')
    op.drop_index(op.f('ix_policyholders_identification_number'), table_name='policy_holders')
    op.drop_index(op.f('ix_policyholders_is_active'), table_name='policy_holders')
    op.drop_index(op.f('ix_policyholders_last_name'), table_name='policy_holders')
    op.create_index(op.f('ix_policy_holders_email'), 'policy_holders', ['email'], unique=True)
    op.create_index(op.f('ix_policy_holders_first_name'), 'policy_holders', ['first_name'], unique=False)
    op.create_index(op.f('ix_policy_holders_id'), 'policy_holders', ['id'], unique=False)
    op.create_index(op.f('ix_policy_holders_identification_number'), 'policy_holders', ['identification_number'], unique=False)
    op.create_index(op.f('ix_policy_holders_is_active'), 'policy_holders', ['is_active'], unique=False)
    op.create_index(op.f('ix_policy_holders_last_name'), 'policy_holders', ['last_name'], unique=False)
    op.alter_column('underwriting_reviews', 'risk_assessment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('underwriting_reviews', 'risk_assessment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.drop_index(op.f('ix_policy_holders_last_name'), table_name='policy_holders')
    op.drop_index(op.f('ix_policy_holders_is_active'), table_name='policy_holders')
    op.drop_index(op.f('ix_policy_holders_identification_number'), table_name='policy_holders')
    op.drop_index(op.f('ix_policy_holders_id'), table_name='policy_holders')
    op.drop_index(op.f('ix_policy_holders_first_name'), table_name='policy_holders')
    op.drop_index(op.f('ix_policy_holders_email'), table_name='policy_holders')
    op.create_index(op.f('ix_policyholders_last_name'), 'policy_holders', ['last_name'], unique=False)
    op.create_index(op.f('ix_policyholders_is_active'), 'policy_holders', ['is_active'], unique=False)
    op.create_index(op.f('ix_policyholders_identification_number'), 'policy_holders', ['identification_number'], unique=False)
    op.create_index(op.f('ix_policyholders_id'), 'policy_holders', ['id'], unique=False)
    op.create_index(op.f('ix_policyholders_first_name'), 'policy_holders', ['first_name'], unique=False)
    op.create_index(op.f('ix_policyholders_email'), 'policy_holders', ['email'], unique=True)
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.alter_column('payments', 'payment_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Store Stripe webhook data and additional info',
               existing_nullable=True)
    op.alter_column('payments', 'failure_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reason for payment failure',
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', 'refunded', 'partially_refunded', 'cancelled', name='payment_status_enum'),
               server_default=sa.text("'pending'::payment_status_enum"),
               existing_nullable=False)
    op.alter_column('payments', 'stripe_charge_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Stripe Charge ID (e.g., ch_...)',
               existing_nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Stripe PaymentIntent ID (e.g., pi_...)',
               existing_nullable=True)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Internal transaction ID',
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'sent', 'paid', 'overdue', 'partially_paid', 'cancelled', 'refunded', name='invoice_status_enum'),
               server_default=sa.text("'pending'::invoice_status_enum"),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date when invoice was fully paid',
               existing_nullable=True)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               comment=None,
               existing_comment='Amount paid so far (supports partial payments)',
               existing_nullable=False)
    op.alter_column('invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Total amount to be paid',
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Format: INV-YYYYMMDD-XXXX',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
